# Generated by Django 3.2 on 2022-02-26 08:22

import core.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=16)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('additional_data', core.fields.JSONField(blank=True, null=True)),
            ],
        ),
    ]
