# Generated by Django 3.2 on 2022-02-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='pt',
        ),
    ]
