# Generated by Django 3.2 on 2022-02-22 11:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='level',
            field=models.CharField(default='info', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='message',
            field=models.TextField(default='test message'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 2, 22, 11, 50, 57, 407315, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
