# Generated by Django 3.2 on 2022-02-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosks', '0005_auto_20220222_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kioskauditlog',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kioskauditlog',
            name='time',
        ),
    ]
