# Generated by Django 3.2 on 2022-02-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosks', '0006_auto_20220222_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiosk',
            name='pt',
        ),
    ]
